// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjscmW7oI_zY7RsVEWHZD5d-M7HGwd0cg',
    appId: '1:768976573254:web:d4b67c1e0e75150e27cb47',
    messagingSenderId: '768976573254',
    projectId: 'promes-abf91',
    authDomain: 'promes-abf91.firebaseapp.com',
    databaseURL: 'https://promes-abf91-default-rtdb.firebaseio.com',
    storageBucket: 'promes-abf91.firebasestorage.app',
    measurementId: 'G-4DQMQ8EJQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAih_6smHI-SBCSeJ1Veci2uX9abhEbkIE',
    appId: '1:768976573254:android:e7e8f3bdd35e9ba627cb47',
    messagingSenderId: '768976573254',
    projectId: 'promes-abf91',
    databaseURL: 'https://promes-abf91-default-rtdb.firebaseio.com',
    storageBucket: 'promes-abf91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3qGZgPzNgQZzTh1ElfyE2x_8bCWRpxBo',
    appId: '1:768976573254:ios:c51cf479317e572d27cb47',
    messagingSenderId: '768976573254',
    projectId: 'promes-abf91',
    databaseURL: 'https://promes-abf91-default-rtdb.firebaseio.com',
    storageBucket: 'promes-abf91.firebasestorage.app',
    iosBundleId: 'com.example.proyek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3qGZgPzNgQZzTh1ElfyE2x_8bCWRpxBo',
    appId: '1:768976573254:ios:c51cf479317e572d27cb47',
    messagingSenderId: '768976573254',
    projectId: 'promes-abf91',
    databaseURL: 'https://promes-abf91-default-rtdb.firebaseio.com',
    storageBucket: 'promes-abf91.firebasestorage.app',
    iosBundleId: 'com.example.proyek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOLCkhYkclIr9R5u5Dfmee-_bpUX8CUjE',
    appId: '1:768976573254:web:1745a67e92c95d8627cb47',
    messagingSenderId: '768976573254',
    projectId: 'promes-abf91',
    authDomain: 'promes-abf91.firebaseapp.com',
    databaseURL: 'https://promes-abf91-default-rtdb.firebaseio.com',
    storageBucket: 'promes-abf91.firebasestorage.app',
    measurementId: 'G-D4BG2Q4062',
  );
}
